In [1]:
from copy import deepcopy

import torch

In [2]:
torch.manual_seed(0);

In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [4]:
from senmodel.model.utils import *

In [5]:
class SimpleFCN(nn.Module):
    def __init__(self, input_size=8):
        super(SimpleFCN, self).__init__()
        self.fc1 = nn.Linear(input_size, 4)
        self.fc2 = nn.Linear(4, 2)
        self.fc3 = nn.Linear(2, 1)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x


model = SimpleFCN()

In [6]:
sparse_model = convert_dense_to_sparse_network(model)

In [7]:
linear = nn.Linear(8, 1)

sparse_weight = dense_to_sparse(linear.weight.data)
sparse_bias = dense_to_sparse(linear.bias.data)
just_sparse_linear = ExpandingLinear(sparse_weight, sparse_bias)

sparse_linear = deepcopy(just_sparse_linear)

print(sparse_linear.weight_indices, "\n")
sparse_linear.replace_many((0, 0), (6, 7))
print(sparse_linear.weight_indices)
print(sparse_linear.embed_linears[0].weight_indices, "\n")

sparse_linear.replace_many((0, 0), (8, 9))
print(sparse_linear.weight_indices)
print(sparse_linear.embed_linears[1].weight_indices, "\n")

print(sparse_linear.weight_indices)
sparse_linear.replace_many((0,), (10,))
print(sparse_linear.weight_indices)
print(sparse_linear.embed_linears[-1].weight_indices, "\n")


# sparse_linear.replace_many((0,), (10,)) # error - no such edge
# print(sparse_linear.weight_indices)
# print(sparse_linear.embed_linears[-1].weight_indices, "\n")



tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4, 5, 6, 7]]) 

tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4, 5, 8, 9]])
tensor([[0, 1],
        [6, 7]]) 

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4,  5, 10, 11]])
tensor([[0, 1],
        [8, 9]]) 

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4,  5, 10, 11]])
tensor([[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4,  5, 11, 12]])
tensor([[ 0],
        [10]]) 



In [8]:
from senmodel.metrics.nonlinearity_metrics import *


In [9]:
criterion = nn.MSELoss()

metrics = [
    GradientMeanEdgeMetric(criterion),
    SNIPMetric(criterion),
    PerturbationSensitivityEdgeMetric(criterion),

]

In [10]:
from torch.utils.data import DataLoader
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression

X, y = make_regression(n_samples=1000, n_features=8, n_informative=8, random_state=42)
X = torch.from_numpy(X).float()
y = torch.from_numpy(y).float()

dataset = list(zip(X, y))
train_dataset, test_dataset = train_test_split(dataset, test_size=0.2, random_state=42)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [11]:

from senmodel.metrics.edge_finder import *

ef = EdgeFinder(metrics[1], test_loader, device=device)

In [12]:
print("values:", ef.calculate_edge_metric_for_dataloader(sparse_linear))
chosen_edges = ef.choose_edges_top_k(sparse_linear, 4)
print("choose:", chosen_edges)

chosen_edges = ef.choose_edges_threshold(sparse_linear, 0.1)
print("choose:", chosen_edges)



values: tensor([0.3037, 0.1075, 0.1085, 0.2672, 0.1222, 0.0667, 0.0206, 0.0036])
choose: tensor([[0, 0, 0, 0],
        [0, 3, 4, 2]])
choose: tensor([[0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4]])


In [13]:
sparse_linear.weight_indices

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4,  5, 11, 12]])

In [14]:
sparse_linear.replace_many(*chosen_edges)

In [15]:
sparse_linear.weight_indices

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 5, 11, 12, 13, 14, 15, 16, 17]])

In [16]:
print("values:", ef.calculate_edge_metric_for_dataloader(sparse_linear))
chosen_edges = ef.choose_edges_top_k(sparse_linear, 5)
print("choose:", chosen_edges)

values: tensor([0.4015, 0.1033, 0.0232, 0.0103, 0.0699, 0.0757, 0.2365, 0.0796])
choose: tensor([[ 0,  0,  0,  0,  0],
        [ 5, 16, 11, 17, 15]])


In [17]:
sparse_linear.replace_many(*chosen_edges)

In [18]:
sparse_linear.weight_indices

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0],
        [12, 13, 14, 18, 19, 20, 21, 22]])

In [19]:
print("values:", ef.calculate_edge_metric_for_dataloader(sparse_linear))
chosen_edges = ef.choose_edges_top_k(sparse_linear, 4)
print("choose:", chosen_edges)

values: tensor([0.0315, 0.0160, 0.1090, 0.2639, 0.3212, 0.1500, 0.0057, 0.1027])
choose: tensor([[ 0,  0,  0,  0],
        [19, 18, 20, 14]])
